OUTPUT_DIR: "../../checkpoint"
OUTPUT_SUB_DIR: 'kidney_using_pretrained_model_ckd_nor'
PRIORITY_CONFIG: True
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 4
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  MASK_ON: True
INPUT:
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
#  PIXEL_MEAN: [0.5, 0.5, 0.5]
#  PIXEL_STD: [0.5, 0.5, 0.5]
#  TO_BGR255: False
DATASETS:
  USE_CATALOG: False
  TRAIN: ("kidney_isangmi_400+100+1200_aki_ckd_train",) # ~/lib/robin_mrcnn/maskrcnn_benchmark/config/paths_catalog.py
  TEST: ("kidney_isangmi_400+100+1200_aki_ckd_val",) # ~/lib/robin_mrcnn/maskrcnn_benchmark/config/paths_catalog.py
DATALOADER:
  SIZE_DIVISIBILITY: 1
  ASPECT_RATIO_GROUPING: False
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000) #(18000,)
  MAX_ITER: 180000 #24000

  CHECKPOINT_PERIOD: 2500
  IMS_PER_BATCH: 4
TEST:
  IMS_PER_BATCH: 4
